backend:
  image:
    repository: asot-backend
    tag: latest
  service:
    type: ClusterIP
    port: 5000

frontend:
  image:
    repository: asot-frontend
    tag: latest
  service:
    type: ClusterIP
    port: 3000